CC = gcc
CFLAGS = -lm
EXECUTABLE = process_grid
OBJECT_DIRECTORY = ./obj
SOURCE_DIRECTORY = .

process_grid: functions.c matsus_grid_processor.c
	$(CC) -o $(EXECUTABLE) $^ 
clean:
	rm new_load_curve_out.dat on_off_data_out.dat heater_schedule.dat heater_switch_matrix.dat process_grid